#!/bin/bash
#
# based on this manual:
# https://grabski.me/tech,/linux/2020/09/02/automatically-unlock-keepassxc-on-startup-and-after-lock-screen/

verify_cmd_exists() {
  command -v "$@" >/dev/null 2>&1 || (echo "$@ not installed" && exit 1)
}

verify_cmd_exists keepassxc || exit 1
verify_cmd_exists secret-tool || exit 1
verify_cmd_exists dbus-send || exit 1
verify_cmd_exists dbus-monitor || exit 1

add() {
    local keepass_db_path="$1"
    secret-tool store --label='KeePassXC Unlocker' service keepassxc-unlocker username "$keepass_db_path"
}

autostart-add() {
    mkdir -p "$HOME/.config/autostart"
    echo \
"[Desktop Entry]
Type=Application
Exec=keepassxc-unlocker startup
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=2 
Hidden=false
NoDisplay=false
Name=keepassxc-unlocker-startup
Name[en_GB]=keepassxc-unlocker-startup
Comment[en_GB]=Launch KeePassXC and unlock databases
Comment=Launch KeePassXC and unlock databases" > "$HOME/.config/autostart/keepassxc-unlocker-startup.desktop"
    echo \
"[Desktop Entry]
Type=Application
Exec=keepassxc-unlocker watch
X-GNOME-Autostart-enabled=true
Hidden=false
NoDisplay=false
Name=keepassxc-unlocker-watch
Name[en_GB]=keepassxc-unlocker-watch
Comment[en_GB]=Launch keepassxc-unlocker watch
Comment=Launch keepassxc-unlocker watch" > "$HOME/.config/autostart/keepassxc-unlocker-watch.desktop"
}

autostart-remove() {
    rm "$HOME/.config/autostart/keepassxc-unlocker-startup.desktop"
    rm "$HOME/.config/autostart/keepassxc-unlocker-watch.desktop"
}

startup() {
    keepassxc &
    sleep 3 # 3 seconds are enough for even flatpak to start
    keepassxc-unlocker unlock
}

unlock() {
    readarray -t secret_to_db_path_arr < <(secret-tool search --all service keepassxc-unlocker 2>&1 \
        | awk '/^secret|^attribute.username/ {print $3}')

    for (( i=0; i<${#secret_to_db_path_arr[@]}; i=$((i+2)) ))
    do
        password=${secret_to_db_path_arr[$i]}
        database=${secret_to_db_path_arr[$i+1]}

        dbus-send --print-reply --dest=org.keepassxc.KeePassXC.MainWindow \
            /keepassxc org.keepassxc.KeePassXC.MainWindow.openDatabase \
            string:"$database" string:"$password"
    done
}

watch() {
    # from here: 
    # https://github.com/keepassxreboot/keepassxc/blob/develop/src/gui/osutils/nixutils/ScreenLockListenerDBus.cpp
    
    trap 'kill 0' EXIT # killing children in case of parent's death

    unlock_on_status() {
        while read; do
            STATUS=$(echo "$REPLY" | awk '/^\s{3}/ {print $2}')
            if [[ "$STATUS" == "$1" ]]; then
                keepassxc-unlocker unlock
            fi
        done
    }

    dbus-monitor --session "type=signal,interface=org.gnome.ScreenSaver,member=ActiveChanged" \
        | unlock_on_status false &
    dbus-monitor --session "type=signal,interface=org.freedesktop.ScreenSaver,member=ActiveChanged" \
        | unlock_on_status false &
    dbus-monitor --session "type=signal,interface=org.xfce.ScreenSaver,member=ActiveChanged" \
        | unlock_on_status false &
    dbus-monitor --session "type=signal,interface=org.gnome.SessionManager.Presence,member=StatusChanged" \
        | unlock_on_status 0 &

    wait
}

case "$1" in
    add)
        add "${@:2}"
        ;;
    autostart)
        case "$2" in
            add)
                autostart-add
                ;;
            remove)
                autostart-remove
                ;;
        esac
        ;;
    startup)
        startup "${@:2}"
        ;;
    unlock)
        unlock "${@:2}"
        ;;
    watch)
        watch "${@:2}"
        ;;
    *)
        echo "Add KDBX unlock password to keyring:"
        echo "   keepassxc-unlocker add <kdbx file path>"
        echo "Add unlocker to autostart:"
        echo "   keepassxc-unlocker autostart add"
        echo "Remove unlocker from autostart:"
        echo "   keepassxc-unlocker autostart remove"
        echo "Start KeePassXC and unlock all kdbx databases keyring has passwords for:"
        echo "   keepassxc-unlocker startup"
        echo "Unlock all kdbx databases keyring has passwords for:"
        echo "   keepassxc-unlocker unlock"
        echo "Run session unlock watcher:"
        echo "   keepassxc-unlocker watch"
        ;;
esac
