#!/bin/bash

IDLE_TIME="300s"
PREFIX="sap"

verify_cmd_exists() {
  command -v "$@" >/dev/null 2>&1 || (echo "$@ not installed" && exit 1)
}

generate() {
  NAME="$PREFIX-$1"
  PROXY_PORT="$2"
  COMMAND="$3"
  SLEEP="$4"
  PORT="$((PROXY_PORT + 1))"
  gen_service "$NAME" "${COMMAND/\%PORT\%/$PORT}" "$SLEEP"
  gen_proxy_service "$NAME" "$PORT"
  gen_socket "$NAME" "$PROXY_PORT"
}

gen_service() {
  NAME="$1"
  COMMAND="$2"
  SLEEP="$3"
  cat >"$HOME/.config/systemd/user/$NAME.service" <<EOF
[Unit]
Description=Tunnel for $NAME

## Stop-when-idle is controlled by \`--exit-idle-time=\` in proxy.service
#  (from \`man systemd-socket-proxyd\`)
StopWhenUnneeded=true

[Service]
Type=simple
## Prefixed with \`-\` not to mark service as failed on net-fails;
#  will be restarted on-demand by socket-activation.
ExecStart=-$COMMAND
## Delay enough time to allow for ssh-authentication to complete
#  so tunnel has been established before proxy process attaches to it,
#  or else the first SYN request will be lost.
ExecStartPost=/bin/sleep $SLEEP
EOF
}

gen_proxy_service() {
  NAME="$1"
  PORT="$2"
  cat >"$HOME/.config/systemd/user/$NAME-proxy.service" <<EOF
[Unit]
Description=Socket-activation proxy for $NAME

## Stop also when stopped listening for socket-activation.
BindsTo=$NAME-proxy.socket
After=$NAME-proxy.socket

## Stop also when ssh-tunnel stops/breaks
#  (otherwise, could not restart).
BindsTo=$NAME.service
After=$NAME.service

[Service]
ExecStart=/lib/systemd/systemd-socket-proxyd --exit-idle-time=$IDLE_TIME 127.0.0.1:$PORT
EOF
}

gen_socket() {
  NAME="$1"
  PROXY_PORT="$2"
  cat >"$HOME/.config/systemd/user/$NAME-proxy.socket" <<EOF
#
# https://unix.stackexchange.com/questions/383678/on-demand-ssh-socks-proxy-through-systemd-user-units-with-socket-activation-does/635178#635178
#
# Check status:
# systemctl --user status $NAME-proxy.{socket,service} $NAME
#
[Unit]
Description=Socket-activation for $NAME

[Socket]
ListenStream=127.0.0.1:$PROXY_PORT

[Install]
WantedBy=sockets.target
EOF
}

verify_cmd_exists xargs || exit 1

# Disable & remove old services
systemctl --user list-unit-files $PREFIX-*.socket --no-legend | awk '{print $1}' | xargs -r systemctl --user disable --now
systemctl --user list-unit-files $PREFIX-* --no-legend |
  awk -v home="$HOME" '{print home "/.config/systemd/user/" $1}' | xargs -r rm
systemctl --user daemon-reload

# Load configs from directory
CONFIG_DIR="$HOME/.config/socket-activation-proxy"
if [ ! -d "$CONFIG_DIR" ] || [ -z "$(ls "$CONFIG_DIR"/*.conf 2>/dev/null)" ]; then
    echo "No config files found in $CONFIG_DIR"
    exit 1
fi
for cfg in "$CONFIG_DIR"/*.conf; do
    source "$cfg"
    FILENAME=$(basename "$cfg")
    SLEEP="${SLEEP:-2}" # Default sleep to 2 if not set
    generate "${FILENAME%.conf}" "$PORT" "$COMMAND" "$SLEEP"
done

systemctl --user daemon-reload
systemctl --user list-unit-files $PREFIX-*.socket --no-legend | awk '{print $1}' | xargs -r systemctl --user enable --now
