#!/bin/bash

command_exists() {
    command -v  "$1" >/dev/null 2>&1 || (echo "$1 isn't installed" && exit 1)
}

command_exists stoken || exit 1
command_exists xclip || exit 1
command_exists secret-tool || exit 1

pin=$(secret-tool lookup service securid-otp)

if [ -z "$pin" ]; then
    set -e
    echo "Token isn't set up. Setting up."
    secret-tool store --label='RSA SecurID PIN' service securid-otp
    pin=$(secret-tool lookup service securid-otp)
    read -p "Enter token url: " -s token_url
    printf "$pin\n$pin\n" | stoken import --token "$token_url" --force > /dev/null
    echo
fi

otp=$(stoken --password=$pin)

echo "$pin$otp" | xclip -selection clipboard
echo "PinToken copied to clipboard. Current OTP: $otp"
